### ISSUE TITLE
[REFACTOR] Auto format RaftStorage when cluster upgrades

### ISSUE THREAD

**Issue by SzyWilliam** [apache/incubator-celeborn#980]
# Motivation
As stated in README,
> If you need to fully restart a Celeborn cluster in HA mode, you must clean ratis meta storage first because ratis meta will store expired states of the last running cluster.

Currently, Ratis provides a FORMAT option when raft storage initializes, see [1]. RaftServer will clean up and format the given storage dir if this option is chosen. Maybe this can save Celeborn from the efforts of deleting files manually. 

[1] https://github.com/apache/ratis/blob/3d546aeba9730a68bf433f166aa76c3fd68c5584/ratis-server-api/src/main/java/org/apache/ratis/server/storage/RaftStorage.java#L55

**Comment by SzyWilliam** [comment]
@pan3793 I would like to try on this issue. Can you assign it to me?

**Comment by pan3793** [comment]
Thanks @SzyWilliam, welcome to Celeborn community!

@waitinfuture we should guide user create issue on JIRA instead of GitHub issue.

And cc @FMX, as you are the main author of this module.

**Comment by waitinfuture** [comment]
Hi @SzyWilliam , thanks for your interest in Celeborn, and we're very glad that you'll work on the ratis issue, which we've tried with no gain. @FMX can provide more details about the problem.
Celeborn has a [jira](https://issues.apache.org/jira/projects/CELEBORN/issues/CELEBORN-11?filter=allopenissues) where we encourage to track bugs and features. We will make it more noticeable on README and Contributing docs.

**Comment by SzyWilliam** [comment]
@waitinfuture Thanks for reminding me of Jira. I'll move this issue to jira later.

**Comment by FMX** [comment]
Hi @SzyWilliam Glad to see your interest.
I'll provide some details about the problems that we encountered. We recommended our users delete the raft meta storage because that we found the Celeborn master will load stats which was generated by last running. We don't want to format the raft storage whenever a master is restarting because the consensus will be lost.

We are facing two major problems in using ratis. We already enable the snapshot mechanism to reduce raft storage size.
1. We found that if we restart the master cluster one by one and the consensus stats will be broken. 
2. We found that if we upgrade a Celeborn master with the old raft storage, the server will not start normally.
